version: '3.7'
services:
  url2img:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: url2img
    ports:
      - 3800:3000
    volumes:
      - /home/devteam/FileVault/url2pdf:/app/uploads
    environment:
      - PORT=3000
    restart: always

